feature_configuration:
  back_end: TF2
  feature_reducer_path: /home/g05-f22/Desktop/ActionSpotting/MyPrototype/SoccerNetPrototype/feature_generation/pca_512_TF2.pkl
  feature_reducer_type: PCA
  features_type: BAIDU
  framerate: 2.0
  grabber: opencv
  input_path: /home/g05-f22/Desktop/ActionSpotting/MyPrototype/SoccerNetPrototype/chunk_generation/generated_chunks/video_chunks/
  output_path: /home/g05-f22/Desktop/ActionSpotting/MyPrototype/SoccerNetPrototype/feature_generation/generated_features/
  overwrite: true
  transform: crop
  video_res: LQ
inference_configuration:
  NMS_threshold: 0.4
  NMS_window: 30
  framerate: 2.0
  input_path: /home/g05-f22/Desktop/ActionSpotting/MyPrototype/SoccerNetPrototype/feature_generation/generated_features/
  num_classes: 17
  output_path: /home/g05-f22/Desktop/ActionSpotting/MyPrototype/SoccerNetPrototype/output_generation/generated_output/
  version: 2
  window_size_frame: 30
model_configuration:
  feature_dim: 512
  framerate: 2
  model_name: NetVLAD++
  num_classes: 17
  pool: NetVLAD++
  vocab_size: 64
  weights: null
  window_size: 15
